inputFiles:
  - README.md.tmpl
outputFiles:
  - README.md
plugins:
  filters: ./get_filter_support_table
  ffprobe: ./get_ffprobe_commands_table
  nu_version:
    cmd: ./bin/nu-version
  example:
    cmd: ./bin/run-example
    #args: []
#pluginTimeout: 10s

